added labels and linegraph to statistic
SG-P13/abi-quiz pull request #121
Opened 2024-09-02 13:51 UTC by CookieDecide

-Added Labels to the bar chart in statistics
-added the lineGraph to the daily task statistics

2024-09-02 16:15 UTC, HDingeldein commented
![image](https://github.com/user-attachments/assets/8d5cb05d-4da6-423a-9185-8815e5466b92)
wenn ich <5 daily tasks gespielt habe bekomme ich so wie hier z.B. den 29.08. ganz hinten angezeigt, obwohl ich am 29.08. den daily task nicht gemacht habe. Würde vorschlagen, dass wir die letzten 5 Tage lückenlos anzeigen und wenn an einem oder mehreren Tagen nicht gespielt wurde wird dort einfach auf 0 gesetzt. (Denke so Zeitsprünge/ Datumsprünge sind allgemein eh nicht so schön in einem Liniendiagramm)

2024-09-02 16:22 UTC, HDingeldein requested changes
Konnte mir zeitlich den Code noch nicht genau anschauen, deshalb erstmal nur der Kommentar als review

2024-09-03 00:09 UTC, CookieDecide commented
War mein Fehler bin davon ausgegangen dass für jeden vergangen Tag lückenlos Einträge in der DB sind aber habs jetzt anders gelöst.
Zeigt jetzt immer die letzten 5 Tage und schaut ob es dazu Einträge in der DB gibt.

2024-09-03 15:51 UTC, HDingeldein approved these changes

2024-09-04 10:46 UTC, merged