18 auswertung nach fragerunde
SG-P13/abi-quiz pull request #25
Opened 2024-06-09 08:52 UTC by HDingeldein

- habe die Auswertung als Scroll View hinzugefügt, da in den meisten Fällen nicht alle beantworteten Fragen auf den Bildschirm passen werden
- die Texte werden aktuell mit ... gekürzt, weil ich es nicht geschafft habe, dass sich die Größe des Textfeldes dynamisch anpasst. Ist denke ich aber als alpha Version so ok
- Besipiellauf (hoffe die Hessenbox funktioniert): https://hessenbox.tu-darmstadt.de/getlink/fiBJJEAzeNoqWQLv6oFSqkTp/Screen_Recording_20240609_103939_Unity%20Remote.mp4

2024-06-10 16:44 UTC, MarcusTU commented on Assets/Scripts/Screen Managers/LinearQuizManager.cs
> +        string givenAnswer = button.GetComponentInChildren<TextMeshProUGUI>().text;
Das würde ich eher via index (in den Daten der Fragen) machen und nicht über den Text des Buttons. Aktuell ist es so, dass dieser Text identisch ist, das muss aber nicht immer so sein (vorallem wenn später Bilder hinzugefügt werden).
Eine Lösung via index wäre robust, egal welches Format die Frage hat (text, bild, etc)

2024-06-10 16:44 UTC, MarcusTU requested changes
Eine einzige Sache (siehe Kommentar) sollte man wahrscheinlich eher anders lösen.

2024-06-11 16:42 UTC, HDingeldein commented on Assets/Scripts/Screen Managers/LinearQuizManager.cs
> +        string givenAnswer = button.GetComponentInChildren<TextMeshProUGUI>().text;
Stimme dir da zu. Habe nur gerade überlegt wie man das umsetzen könnte und glaube? das ist beim aktuellen Stand etwas schwierig, weil ich ja über den Button keinen Zugriff mehr auf die question + answer und damit die answerId habe. Das einzige was man machen könnte wäre über den Antwort Text wieder die id aus dem Katalog im Speicher zu holen, dann die id abzuspeichern und dann später wieder über die id das Bild/ Text holen? und das wäre glaube ich ein bisschen Fehleranfällig und auch irgendwie unnötig umständlich. Aktuell werden ja einfach nur Texte auf den Buttons platziert. Ich weiß nicht, wie das aussieht, wenn da dann Bilder drauf sind (ist das dann auch TextMeshProUGUI?), sonst könnte man ja abfragen, ob ein Text existiert und falls nicht dann das Bild abfragen.
Oder hast du eine Idee wie man das mit den Indizes sinnvoll machen könnte?

2024-06-11 19:01 UTC, MarcusTU commented on Assets/Scripts/Screen Managers/LinearQuizManager.cs
> +        string givenAnswer = button.GetComponentInChildren<TextMeshProUGUI>().text;
Dann habe ich wohl etwas missverstanden. Mein Gedankengang war: Die richtige Antwort ist "immer" button[0] richtig ist und sich dadurch irgendwas vereinfacht (also beim Fragenkatalog ist immer Antwort mit Index 0 korrekt) :)
Die Idee wäre dann DataManager.AddAnswer folgendes Interface zu geben: AddAnswer(questionIndex, answerIndex). (isCorrect ergibt sich dann aus "answerIndex == 0" und muss nicht übergeben werden).
Man braucht also irgendwo den questionIndex hinterlegt, der answerIndex ist einfach die Nummer des angeklickten Buttons.

2024-06-12 12:53 UTC, dmc1011 commented on Assets/Scripts/Screen Managers/LinearQuizManager.cs
> +        string givenAnswer = button.GetComponentInChildren<TextMeshProUGUI>().text;
um den Fragenindex der aktuellen Frage zu bekommen können wir nextQuestionIndex - 1 verwenden. das sollte zum Zeitpunkt des Methodenaufrufs der korrekte Fragenindex sein

2024-06-12 15:48 UTC, dmc1011 approved these changes

2024-06-12 17:46 UTC, MarcusTU approved these changes

2024-06-12 18:32 UTC, merged