7 navigation initiale screens
SG-P13/abi-quiz pull request #9
Opened 2024-05-27 15:51 UTC by MarcusTU

Es ist leider etwas mehr als nur "initiale screens" geworden, sondern eher ein Grundgerüst.

2024-05-28 20:27 UTC, dmc1011 requested changes
@MarcusTU @ZhaoJinsi @CookieDecide @HDingeldein 
Bitte schaut euch meine Kommentare an, manches sind nur "Kleinigkeiten", aber es ist viel angenehmer wenn wir unser Projekt/Code von Anfang an clean halten. Bezüglich funktionaler Änderungen müssen nicht alle zwangsläufig jetzt gemacht werden, das kann der auch der/diejenige übernehmen, der dann an den jeweiligen Features weiterarbeitet. Wollte euch aber meine Ansichten mitteilen und absprechen bevor wir das alles mergen.

Bezüglich des UIs: Erstellen/Verwenden von Prefabs wäre sinnvoll, kann aber auf ein neues Ticket mit neuem Branch verschoben werden

Edit: sehe gerade dass ich die Kommentare unter die betroffene Codezeile hätte machen müssen, damit die Vorschau passt. Naja beim nächsten mal...

2024-05-28 20:27 UTC, dmc1011 commented on Assets/Scripts/SingleplayerGameloop1Manager.cs
> +
- Screenwechsel komplett von Beantwortung der Fragen trennen (-> "nächste Frage" Button), kann dann in Zukunft mit direktem Feedback zu Richtigkeit der gegebenen Antwort kombiniert werden, damit die Spieler in eigenem Tempo die Fragen wechseln können (Ziel ist schließlich der Lernfaktor)
- extra Button in Screen_GameplayLoop1 um zurück zum Hauptmenü bzw Ergebnisübersicht zurückzukehren

2024-05-28 20:27 UTC, dmc1011 commented on Assets/Scripts/UIDesign.cs
> +
- englische Benennungen in gesamter Klasse

2024-05-28 21:57 UTC, MarcusTU commented on Assets/Scripts/DataManager.cs
> +
Das kommt darauf an "wie viel Speicher" die Fragenkataloge später haben. Wenn wir nur bei Text bleiben ist es kein Problem alles auf ein Mal zu laden. Sobald Bilder im Spiel sind nicht mehr.

2024-05-28 22:21 UTC, MarcusTU commented on Assets/Scripts/DropdownManager.cs
> +    private string scene;
Das kommt weg. "ButtonManager", "Labelmanager", "DropdownManager" ist dann obsolet.

2024-05-28 22:24 UTC, MarcusTU commented on Assets/Scripts/LabelManager.cs
> +    private string scene;
"me" kann man wie "this" verstehen, daher der Name. Da die Manager eh weg kommen ist das egal.

2024-05-28 22:39 UTC, MarcusTU commented on Assets/Scripts/DataManager.cs
> +    }
Die Idee dahinter war, dass Bilder und Text "quasi gleichberechtigt" sein sollen (also sowohl für Fragen, als auch für Antworten). Daher war es (aus meiner Sicht) logisch eine Struct so zu erstellen die beides kapselt, sodass sich der Rest des Programms nicht mehr damit auseinandersetzen muss (da fehlen natürlich noch geeignete Methoden für "ImageOrText", aktuell ist da ja nichts drin). Wenn wir sowieso beides supporten wollen sehe ich zumindest keine "Nachteile" in diesem Vorgehen.

2024-05-29 05:40 UTC, HDingeldein commented on Assets/Scripts/DataManager.cs
> +
Hatte/ Habe vor das so zu implementieren, dass einzelne Fragenkataloge geladen werden. Werde "Data" bzw. eigentlich den ganzen DataManager dazu etwas umbauen

2024-05-29 11:41 UTC, dmc1011 commented on Assets/Scripts/LabelManager.cs
> +    private string scene;
schon klar, dass es gleichwertig zu this gemeint ist, mein Gedanke war aber, dass man leicht die Vorstellung verliert was hinter me steckt, wenn es in einem so großen Kontext verwendet wird weil man den Kontext so nicht direkt sieht (wie z.B. wenn es innerhalb einer kleinen Funktion oder mit objectXY.me aufgerufen werden würde). 

Außerdem kann es verwirrend sein, weil mit this das Script selbst referenziert wird und daher "me" schnell falsch interpretiert werden kann. Aber wenn es weg kommt ist es egal.

2024-05-29 13:49 UTC, HDingeldein approved these changes

2024-05-29 14:00 UTC, dmc1011 approved these changes

2024-05-29 14:01 UTC, merged